### ISSUE TITLE
Bug: Error: Wiki folder is not empty

### ISSUE THREAD

**Issue by kookma** [Telumire/TWNodeJSLauncher#1]
### Describe the bug

Starting launcher as below

```
TWNodeJSLauncher.bat myWiki
```

The batch file creates the new wiki folder `myWiki` and lauches TiddlyWiki successfuly!

Next time, when I want to launch `myWiki`, I use the below two methods:

1. open `myWIki` folder and run `start.bat`
2. open the parent folder and run `TWNodeJSLauncher.bat myWiki`

Both return the below error message while launch myWIki:

`
Error: Wiki folder is not empty
`

### Platforms

Windows 10, Chrome, TW 5.2.7

### Browsers

Chrome/Edge 110

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by Telumire** [comment]
Hi @kookma , yes it does produce an error in the console, but this does not seem to have any ill effect, as far as I can tell. I'll try to fix this, if you have any idea why this happens feel free to open a pr :)

**Comment by kookma** [comment]
Hi @Telumire 

Thank you

I think the script can check if the folder is existed and has a tiddlywiki.info to launch it!
In there is no such folder create it!

**Comment by Telumire** [comment]
@kookma I used chatgpt to help me correct the code, now it will check if the folder is empty before using the command "tiddlywiki "%name%" --init server". Should be fixed, let me know if you spot another issue ;)

**Comment by kookma** [comment]
Works like a charm! 

Much appreciated!
